### ISSUE TITLE
The XML in the uploaded file could not be parsed.

### ISSUE THREAD

**Issue by aligliotoi** [slashme/parliamentdiagram#124] opened 2022-04-27 12:57 UTC
Hi, can anybody explain me what is wrong with my .svg?

![svgfiles_2022-04-27-12-42-54-455343-8820676777352720020](https://user-images.githubusercontent.com/104505789/165523037-2c700c22-1319-4059-aad5-d1ade5c799dd.svg)

**Comment by slashme** [comment] 2022-06-16 12:58
This was an issue with unicode in party names. Duplicate of #110 which has now been fixed. Thank you for the clear bug report!

**Closed by slashme** 2022-06-16 12:58 UTC
