### ISSUE TITLE
Does not work, not sure whats going on 

### ISSUE THREAD

**Issue by Garvey64** [slashme/parliamentdiagram#122] opened 2022-04-03 18:24 UTC
sometimes it'll throws me an error message, other times it with give me
 a half-filled image with an error message. Its saying i might have over 30,000 some seats, but im fairly sure 577 is less than 31,000. 
![image](https://user-images.githubusercontent.com/54291889/161442466-26130981-bccc-4c75-87b4-578c6d0c31fb.png)
![image](https://user-images.githubusercontent.com/54291889/161442475-9c025e45-0c26-4196-a4a1-1183f3ce718f.png)
![svgfiles_2022-04-03-18-22-44-229828-1227778992831468071](https://user-images.githubusercontent.com/54291889/161442483-43fbe578-e8e2-42d1-ad94-cd12bd28665a.svg)

**Comment by slashme** [comment] 2022-06-16 12:56
This was an issue with unicode characters - duplicate of #110 which is now fixed.

**Closed by slashme** 2022-06-16 12:56 UTC
