### ISSUE TITLE
Adding the Get Parties List to Westminster

### ISSUE THREAD

**Issue by nate56mate** [slashme/parliamentdiagram#80] opened 2020-09-27 04:40 UTC
I think adding the Get Parties List from Images to the Westminster generator will make it easier for people who want to recreate the British or Australian Parliaments without having to manually adding the party colors.

**Comment by slashme** [comment] 2020-10-02 05:03
I'm marking this as a duplicate of #41 . Definitely high on my to-do list!

**Closed by slashme** 2020-10-02 05:03 UTC
